apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: cert-manager
spec:
  limits:
  - default:
      cpu: 100m
      memory: 100Mi
    defaultRequest:
      cpu: 100m
      memory: 100Mi
    type: Container
